### ISSUE TITLE
Error: Cannot find module 'prompt'

### ISSUE THREAD

**Issue by huuanh1987** [FabioAntunes/fish-nvm#35]
internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:43:14)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)

Can you help me ?

**Comment by FabioAntunes** [comment]
try updating to the latest version of `fish-nvm`

When is this happening? When you run `node` REPL

**Comment by FabioAntunes** [comment]
Closing this, feel free to re open it if you still have this issue
